# URLs
url:
  csrf-token-url: https://bap.bemo.cloud/web/login
  login-url: https://bap.bemo.cloud/web/login
  attendance-list-url: https://bap.bemo.cloud/web/dataset/search_read
  im-status-url: https://bap.bemo.cloud/longpolling/im_status
# User Information
user:
  username: <username>
  password: <password>