# URLs
url:
  attend-url: https://bap.bemo.cloud/web/dataset/call_kw/hr.employee/attendance_manual
  attendance-list-url: https://bap.bemo.cloud/web/dataset/search_read
  csrf-token-url: https://bap.bemo.cloud/web/login
  im-status-url: https://bap.bemo.cloud/web/dataset/call_kw/ir.ui.menu/load_menus_root
  login-url: https://bap.bemo.cloud/web/login

# User Information
user:
  password: <password>
  username: <username>

# Working time
working-time:
  morning:
    start: '8:15'
    end: '12:00'
  afternoon:
    start: '13:15'
    end: '17:30'

#Mail
mail:
  smtp-server: smtp.gmail.com
  port: 587
  sender-email: <sender email>
  sender-name: BEMO
  password: <password>
  receiver-email: <receiver email>
